import Head from "next/head";

import { Button, Divider } from "antd";

export default function SignUP() {
  return (
    <>
      <Head>
        <title>Online Shopping</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Oswald:wght@200&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;1,100;1,300;1,400;1,500;1,700&family=Urbanist:wght@100&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <div className="mainSection">
        <div className="leftMain">
          <div className="headerContent">
            <div>
              <img src="/Frame1.png" />
            </div>
          </div>
          <div className="leftCenter">
            <div className="signUpContent">
              <h1> Sign Up </h1>
              <div className="button">
                <Button value="default">
                  <img className="img" src="/Union1.png" />
                  Google
                </Button>
                <Button value="default">
                  <img className="img" src="/Union2.png" />
                  Linkedin
                </Button>
              </div>

              <Divider className="topContent">or sign up with email</Divider>

              <div className="inputField">
                <label>Email</label>
                <input placeholder="info@gmial.com" />
                <Button type="primary" className="continueBtn">
                  <p className="">Continue</p>
                </Button>
              </div>
              <Divider className="bottoncontent">
                {" "}
                Already have an account?
              </Divider>
              <Button type="primary" className="signInbtn">
                <p className="signIn">Sign In</p>
              </Button>
            </div>
          </div>
        </div>
        <div className="rightSide">
          <div className="rightImage">
            <div className="rightImg"> </div>
            <div className="rightImageText">
              "Good design is not just what looks good. It also needs to
              perform, convert, astonish, and fulfill its purpose."
              <div className="textAuthor">Ahmed - Brand Designer</div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
