import Head from 'next/head'
import { Button } from 'antd'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
       <h1> Hellow World!</h1>
       <Link href= "/about/about">
         <h1> gO To About</h1>
       </Link>
       <Link href= "/content-demo/contentfull">
       <Button type="primary">Primary Button</Button>
       </Link>
      </main>
    </>
  )
}

